// Export all SVG icons from the icons directory as React components
export { default as ActiveIcon } from './active.svg';
export { default as ApprovedIcon } from './approved.svg';
export { default as Check1Icon } from './check-1.svg';
export { default as Check2Icon } from './check-2.svg';
export { default as Check3Icon } from './check-3.svg';
export { default as ChevronIcon } from './chevron.svg';
export { default as ClockIcon } from './clock.svg';
export { default as CompletedIcon } from './completed.svg';
export { default as DeletedIcon } from './deleted.svg';
export { default as DraftsIcon } from './drafts.svg';
export { default as EarthIcon } from './earth.svg';
export { default as EmailIcon } from './email.svg';
export { default as Examples1Icon } from './examples-1.svg';
export { default as Examples2Icon } from './examples-2.svg';
export { default as Examples3Icon } from './examples-3.svg';
export { default as Examples4Icon } from './examples-4.svg';
export { default as Examples5Icon } from './examples-5.svg';
export { default as Examples6Icon } from './examples-6.svg';
export { default as Guarantee1Icon } from './guarantee-1.svg';
export { default as Guarantee2Icon } from './guarantee-2.svg';
export { default as Guarantee3Icon } from './guarantee-3.svg';
export { default as Guarantee4Icon } from './guarantee-4.svg';
export { default as HiddenIcon } from './hidden.svg';
export { default as InactiveIcon } from './inactive.svg';
export { default as LinkedinIcon } from './linkedin.svg';
export { default as LiveIcon } from './live.svg';
export { default as Logout1Icon } from './logout-1.svg';
export { default as Logout2Icon } from './logout-2.svg';
export { default as MinusIcon } from './minus.svg';
export { default as OneIcon } from './one.svg';
export { default as Perfect1Icon } from './perfect-1.svg';
export { default as Perfect2Icon } from './perfect-2.svg';
export { default as Perfect3Icon } from './perfect-3.svg';
export { default as Perfect4Icon } from './perfect-4.svg';
export { default as PhoneCallIcon } from './phone-call.svg';
export { default as PlusIcon } from './plus.svg';
export { default as PriceTagIcon } from './price-tag.svg';
export { default as Processing1Icon } from './processing-1.svg';
export { default as Processing2Icon } from './processing-2.svg';
export { default as RejectedIcon } from './rejected.svg';
export { default as SavedIcon } from './saved.svg';
export { default as ScheduledIcon } from './scheduled.svg';
export { default as SearchIcon } from './search.svg';
export { default as UpdatingIcon } from './updating.svg';
export { default as ViewIcon } from './view.svg';
export { default as Warning1Icon } from './warning-1.svg';
export { default as Warning2Icon } from './warning-2.svg';
export { default as Why1Icon } from './why-1.svg';
export { default as Why2Icon } from './why-2.svg';
export { default as Why3Icon } from './why-3.svg';
export { default as Why4Icon } from './why-4.svg';
export { default as YouGet1Icon } from './you-get-1.svg';
export { default as YouGet2Icon } from './you-get-2.svg';
export { default as YouGet3Icon } from './you-get-3.svg';
export { default as YouGet4Icon } from './you-get-4.svg';
export { default as Logo } from './logo.svg';
export {default as Dark1Icon } from './1-dark.svg';
export {default as Dark2Icon } from './2-dark.svg';
export {default as Dark3Icon } from './3-dark.svg';
export {default as Dark4Icon } from './4-dark.svg';
export {default as Light1Icon } from './1-light.svg';
export {default as Light2Icon } from './2-light.svg';
export {default as Light3Icon } from './3-light.svg';
export {default as Light4Icon } from './4-light.svg';
export {default as BagIcon } from './bag.svg';
export {default as ChartIcon } from './chart.svg';
export {default as TargetIcon } from './target.svg';
export {default as MoneyIcon } from './money.svg';
export {default as SettingsIcon } from './settings.svg';
export {default as GrowIcon } from './grow.svg';
export {default as PrizeIcon } from './prize.svg';
export {default as UserSettingsIcon } from './userSettings.svg';
export {default as ThinkingIcon } from './thinking.svg';
export {default as AiIcon } from './ai.svg';
export {default as DesktopIcon } from './desktop.svg';
export {default as MeetingIcon } from './meeting.svg';
export {default as ToolsIcon } from './tools.svg';
export {default as FilterIcon } from './filter.svg';
export {default as BrowserIcon } from './browser.svg';
export {default as MessagesIcon } from './messages.svg';
export {default as BuildingIcon } from './building.svg';
export {default as PriceIcon } from './price.svg';
export {default as TimeIcon } from './time.svg';
export {default as LogoSmall } from './logo-small.svg';