name: Vercel Prod Deploy (on main)
on:
  push:
    branches: [ "main" ]
jobs:
  trigger-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Deploy Hook
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
